apiVersion: v1
kind: Pod

metadata:
  name: myprobe-pod
  labels:
    app: probe-yellow-pod

spec:
  containers:
    - name: myyellow-container
      image: longflew/ingress:YELLOWPAGE

      ports:
        - containerPort: 80

      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10

      livenessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10